services:
  mongodb:
    image: mongo
    container_name: "mongodb-echo"
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: "habicool"
      MONGO_INITDB_ROOT_PASSWORD: "habixz1234"
  mongo-express:
    image: mongo-express
    container_name: "mongoexpress-echo"
    restart: no
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin-habicool"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin-habixz1234"
      ME_CONFIG_MONGODB_URL: "mongodb://habicool:habixz1234@localhost:27017/"